apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
type: "kubernetes.io/rbd"  
data:
  key: QVFBbk1MaGNBV2laSGhBQUVOQThRWGZyQ3haRkJDNlJaWTNJY1E9PQ==  
  # 使用时需要替换为grep key /etc/ceph/ceph.client.admin.keyring |awk '{printf "%s", $NF}'|base64 结果
