apiVersion: v1
kind: Service
metadata:
  name: galera
  namespace: galera
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
    clusterIP: None
      selector:
        app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ops
  namespace: galera
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
